language: node_js
node_js:
  - '4'
  - '5'
before_install:
  - npm install -g grunt-cli
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - grunt test
env:
  global:
    - secure: qjMwfcWDzEhGWxVhmGi5s0MlsU4N/SI96mx6Gj36/GySxgIUU9EFXeN4SZS2OvRmy2/+l0XSt5ln9PWp4Suh2LM8/GaR5I6FALs/9rOLU9py0/G9V1ImqNN9Z6Nk6PvS71SAwP7xOtR+xsywnUEdHZ7dCA3fYEIsOkyq4KRQ9M7JHWogP+h+WsHPcznjPeNxVBCfYCXW0KhrLDzL4ZA+b2UY/IMZDXITdZ99TZQA6XSKTfJg3xs/jqXEo91igHNKN6VxappBqPbDiFxf7az1RExq3oHAawCDTaKE7xxip+6UIxAeo63tiM0vgp92HVrVsIQETSQFBP4aqhl/pfxQ7d9lto7Mz5AlxKvJ3CIwDD/hspPzG5SNrj/FgQLgK7LrUOomMOjf8giRUg8XXLe7Rb1jmbePP3Z9DIEg4Z+ar3dpC2dNiWYFwBM14wY39GuU6tJpzImGRRUGCMPiO55TVTdRZacVeIq1XWRecIH0CabZThJCwOxyiGIT5ETiT5CVs0CgnbVe99l1qyi8wrMnbw4m4UAlMQ/5kytqtsL957RwxvcctCtX+LlshAgC3m1Aq/aF8V/wIYDcRlwOY2HbGiFQJewV7Aeln3t/S8VFjP9hHn8ZTsH9ez3VB57Q53YgrxFCr6CXEK4X3dkmRpx9in3oDI51TxW32tInwGTukSg=
    - secure: iaTZRzv9ptLHYsDxyM9JaBO+hfQuD36V9THl4z/0xwVUXcegVL7SiPPW/P1nQiV3w8MfWGbJAlsw08kk/uz+0afosx5GzOp+XonUCeiC5xmTH1zJzrGJh0GI+/45bQp24xdNO3YmPcrX5+CPf8MF7L9as4uzWqHTzpwOCFXZUsIZ5fNaLLmD/xH4WyoP8YViYDs5YFGH8+G/gW6uA4sL7U57GpGsYcfHafUeBmAkwiKy5nz9GcdSdPK1aas29EyfVvq8L0SyQpDJodO6Z4AGzWG5BUgZzzfm/KbCtMIMuCF6XC/dU7nFR8jbd8lZ7NnUS/qfLjNVma8CUhHwime2PfPCHV39DVvNMWQCHhHY1ls+CZbxT7Gz1vppVkbTlFslHpDQr/nGFMjd6BDgzaQCnGz+QggMAqSMDvxMQktC52VkctL6MBSay+YsFDc7VJUWkaLWoS0ezM1QTcKZPCJJKDI21zx0x1jjmOW/R7YRXHwS7rdFsqRP9gK4MfUNRa6Rsqk2CXOo94+uljHqcdvN6A94HoivCT+Rx2jfcvu1O0J9dp5/THaXxJ0y9uEAIJnYgZUSUk+QHIe8Bs/S95xfNyDcdPjgAMEHiOzqWjBWxFiaQoloWJg9Okyx/3wwhVmB5eS1ww6OVEI8K/by/ulf2xeffmOW8snODofEH1/mfw4=
